dist: xenial

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO_VERSION="<1.9" MJML_VERSION=3.3.5
  - DJANGO_VERSION="<1.9" MJML_VERSION=4.3.1
  - DJANGO_VERSION="<1.9" MJML_VERSION=4.4.0

  - DJANGO_VERSION="<1.10" MJML_VERSION=3.3.5
  - DJANGO_VERSION="<1.10" MJML_VERSION=4.3.1
  - DJANGO_VERSION="<1.10" MJML_VERSION=4.4.0

  - DJANGO_VERSION="<1.11" MJML_VERSION=3.3.5
  - DJANGO_VERSION="<1.11" MJML_VERSION=4.3.1
  - DJANGO_VERSION="<1.11" MJML_VERSION=4.4.0

  - DJANGO_VERSION="<1.12" MJML_VERSION=3.3.5
  - DJANGO_VERSION="<1.12" MJML_VERSION=4.3.1
  - DJANGO_VERSION="<1.12" MJML_VERSION=4.4.0

  - DJANGO_VERSION="<2.1" MJML_VERSION=3.3.5
  - DJANGO_VERSION="<2.1" MJML_VERSION=4.3.1
  - DJANGO_VERSION="<2.1" MJML_VERSION=4.4.0

  - DJANGO_VERSION="<2.2" MJML_VERSION=3.3.5
  - DJANGO_VERSION="<2.2" MJML_VERSION=4.3.1
  - DJANGO_VERSION="<2.2" MJML_VERSION=4.4.0

  - DJANGO_VERSION="<2.3" MJML_VERSION=3.3.5
  - DJANGO_VERSION="<2.3" MJML_VERSION=4.3.1
  - DJANGO_VERSION="<2.3" MJML_VERSION=4.4.0

matrix:
  exclude:
    - { python: "2.7", env: DJANGO_VERSION="<2.1" MJML_VERSION=3.3.5 }
    - { python: "2.7", env: DJANGO_VERSION="<2.1" MJML_VERSION=4.3.1 }
    - { python: "2.7", env: DJANGO_VERSION="<2.1" MJML_VERSION=4.4.0 }

    - { python: "2.7", env: DJANGO_VERSION="<2.2" MJML_VERSION=3.3.5 }
    - { python: "2.7", env: DJANGO_VERSION="<2.2" MJML_VERSION=4.3.1 }
    - { python: "2.7", env: DJANGO_VERSION="<2.2" MJML_VERSION=4.4.0 }

    - { python: "2.7", env: DJANGO_VERSION="<2.3" MJML_VERSION=3.3.5 }
    - { python: "2.7", env: DJANGO_VERSION="<2.3" MJML_VERSION=4.3.1 }
    - { python: "2.7", env: DJANGO_VERSION="<2.3" MJML_VERSION=4.4.0 }

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8

install:
  - npm install mjml@$MJML_VERSION
  - node_modules/.bin/mjml --version
  - pip install "Django$DJANGO_VERSION"

script:
  - python tools.py test
