language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION="<1.9" MJML_VERSION=2.3.3
  - DJANGO_VERSION="<1.9" MJML_VERSION=3.0.2
  - DJANGO_VERSION="<1.9" MJML_VERSION=3.1.1
  - DJANGO_VERSION="<1.9" MJML_VERSION=3.2.2

  - DJANGO_VERSION="<1.10" MJML_VERSION=2.3.3
  - DJANGO_VERSION="<1.10" MJML_VERSION=3.0.2
  - DJANGO_VERSION="<1.10" MJML_VERSION=3.1.1
  - DJANGO_VERSION="<1.10" MJML_VERSION=3.2.2

  - DJANGO_VERSION="<1.11" MJML_VERSION=2.3.3
  - DJANGO_VERSION="<1.11" MJML_VERSION=3.0.2
  - DJANGO_VERSION="<1.11" MJML_VERSION=3.1.1
  - DJANGO_VERSION="<1.11" MJML_VERSION=3.2.2

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

install:
  - npm install mjml@$MJML_VERSION
  - node_modules/.bin/mjml --version
  - pip install "Django$DJANGO_VERSION"

script:
  - python tools.py test
